### ISSUE TITLE
How is the JS code sandboxed?

### ISSUE THREAD

**Issue by spolu** [Bromeon/js-sandbox#14]
Hi! Very nice project. 

I was looking at the script.rs code and couldn't quite understand how the JS code is sandboxed. Is the sandboxing coming from the default Deno runtime configuration? What are the guarantees we can assume here? 

Thank you!

**Comment by Bromeon** [comment]
Yes, Deno takes care of the sandboxing.
On [its homepage](https://deno.land/), the mission statement includes:
> * Secure by default. No file, network, or environment access, unless explicitly enabled.

More detailed information can be found on the [Permissions page](https://deno.land/manual@v1.24.3/getting_started/permissions). Those are not (yet?) provided by js-sandbox though.

**Comment by spolu** [comment]
Thanks! Very useful!
