### ISSUE TITLE
When will the package be updated?

### ISSUE THREAD

**Issue by rscarson** [Bromeon/js-sandbox#17]
It has been over a year since the last published version - in December a changed was merged in I have been waiting for, but it has yet to make it to the published package version

Will this package be receiving further updates, or should be moving to a different crate?

**Comment by Bromeon** [comment]
I can release another version later this week or next week, if that helps 🙂

Out of curiosity, how do you use js-sandbox at the moment?

**Comment by rscarson** [comment]
For my package [lavendeux-parser](https://github.com/rscarson/lavendeux-parser)

I am using to let users extend functionality at runtime with JS

I have wanted a way to extend that to network ops, which would require async functionality

**Comment by Bromeon** [comment]
Apologize for the delay, version [`0.2.0-rc.1`](https://docs.rs/js-sandbox/0.2.0-rc.1) is now released (docs.rs still pending).

I plan to soon release `0.2.0` with minor API changes.
