### ISSUE TITLE
'export' keyword not supported

### ISSUE THREAD

**Issue by rscarson** [Bromeon/js-sandbox#19]
Having exports in a script being run through js-sandbox results in ```Uncaught SyntaxError: Unexpected token 'export'```

Makes it difficult to test scripts designed to run through the crate

**Comment by rscarson** [comment]
Ok so for that feature to work you'd need to switch from scripts to modules, so in ```script.rs: create_script``` you'd need to add a module loader with ```options.module_loader = Some(Rc::new(FsModuleLoader));```

Then you replace execute_script with:
```
let module_id = runtime.load_main_module(&Url::parse(js_filename)?, Some(js_code.to_string())).await.unwrap();
runtime.mod_evaluate(module_id);
```

HOWEVER that makes the whole function asynchronous, which is a problem. You could bridge it with channels, but it may be too large a project to be worthwhile? I'm using globals instead of exports for now instead

**Comment by Bromeon** [comment]
This seems to be a more specialized problem of #2, no? As such, it would probably need some design for modules.

Disclaimer: my time to maintain `js-sandbox` is a bit limited at the moment, and it will be difficult for me to implement larger features from scratch. Also, I'm more a Rust than a JS guy😉But I'd be happy to accept pull requests if they fit the scope of the library (sandboxing, unidirectional Rust->JS interaction, easy-to-use) 🙂
