### ISSUE TITLE
Will there be another release on crates.io?

### ISSUE THREAD

**Issue by bolshoytoster** [Bromeon/js-sandbox#24]
The current 'stable' (0.1.6) release of this project is over 2 years old, and depends on a horrendously old version of deno_core (0.84.0), which depends on an even more old rusty_v8 (0.22.3).

This has worked perfectly fine for me, [until rust changed the size of `TypeId`s in nightly](https://github.com/rust-lang/compiler-team/issues/608), which causes [an assertion](https://github.com/denoland/rusty_v8/blob/8c79145f59e22d0f42829957889e0be66e1984b3/src/support.rs#L556) in said version of rusty_v8 to fail, panicing.

I can solve this by using an older compiler, but making a new release would make sure others are less likely to run into this issue in the future. (It would also bring recent performance boosts from deno and rusty_v8 as well)

**Comment by bolshoytoster** [comment]
I'm using the current git version of this project, and I get a compilation error for the same reason, it looks like it's fixed in [this PR on the v8 repo](https://github.com/denoland/rusty_v8/pull/1249), so the version of deno_core depended on should be updated to one after the 15th of July to apply the fix.

My solution in the mean time is to use an older nightly compiler.

**Comment by Bromeon** [comment]
Note that there are 2 experimental releases on crates.io, the last one from April this year 🙂 

A 0.2.0 release should be possible, but to clean up some APIs I'd need to invest a bit more time, which I don't have this week. It also depends on how much effort the `deno_core` update would be. I'll try to have a look next week.

**Comment by bolshoytoster** [comment]
@Bromeon
> It also depends on how much effort the deno_core update would be.

I'd be willing to try it if you don't have the time.

**Comment by Bromeon** [comment]
If you have the time and motivation, a PR would definitely be welcome! ❤️

**Comment by bolshoytoster** [comment]
@Bromeon I've updated the dependency, but the tests are failing with a `SIGSEGV: invalid memory reference` because of a bug in deno. I'm going to open an issue there.

Should I still open a PR for this or wait until it's fixed?

**Comment by Bromeon** [comment]
Thanks so much! 💪 

> Should I still open a PR for this or wait until it's fixed?

That's up to you, from my side there's no urgency.

**Comment by bolshoytoster** [comment]
@Bromeon I did some testing and found that `deno_core = "0.200"` does not have this crash, so I'll open a PR with that version.

**Comment by rscarson** [comment]
Can I get a timeline for the release of the next RC version? I haven't been able to publish updates to my crate in months

If it will be much longer, would you mind if I temporarily published my fork of this just so I can resume work?

**Comment by bolshoytoster** [comment]
@rscarson until the next release you should be able to use the git version (`js-sandbox = { git = "https://github.com/Bromeon/js-sandbox" }`), to avoid having to publish a fork.

**Comment by rscarson** [comment]
Don't think you can publish crates that have a GitHub dependency

**Comment by Bromeon** [comment]
Sorry about the delays, I can publish today evening. Is current `master` suitable?

**Comment by rscarson** [comment]
Yup!
