### ISSUE TITLE
could not compile `rusty_v8`

### ISSUE THREAD

**Issue by rsdte** [Bromeon/js-sandbox#5]
error description:  
   I copied the example from the README, and then I encountered this error when compiling and running.

my current enviroment:  
        system version: Windows 11 22000.184  
       rustc version: rustc 1.54.0  
       cargo version: cargo 1.54.0  

```toml
[package]
name = "jsdemo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sandbox = "0.1.6"
```

```rust
use js_sandbox::{Script, AnyError};

fn main() -> Result<(), AnyError> {
	let src = r#"
		function toString(person) {
			return "A person named " + person.name + " of age " + person.age;
		}"#;

	let mut script = Script::from_string(src)
		.expect("Initialization succeeds");
	Ok(())
}
```

more info
```powershell
PS F:\repos\rust\jsdemo> cargo build    
   Compiling rusty_v8 v0.22.3
   Compiling serde_v8 v0.2.0
   Compiling deno_core v0.84.0
error: could not find native static library `rusty_v8`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `rusty_v8`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by Bromeon** [comment]
Strange, I cannot reproduce it on Windows 10.
What I did:
```bash
cargo new --bin project
cd project
cargo add js-sandbox
# then, replace main.rs's contents with the example code in your message
cargo run
```
I get warnings for unused mut/variable, but no errors. It might be that Windows 11 changes some things in this regard.

If you create an empty project and add `deno_core` or `rusty_v8` directly, does it work?
What if you use exactly the same versions as `js-sandbox`?

**Comment by rsdte** [comment]
Adding these two packages separately in the new project also reported the same error.
Do I need to install other additional packages or software?

**Comment by Bromeon** [comment]
Does `rusty_v8` trigger the issue alone, also when you update it to its latest version?

I was under the impression that `rusty_v8` automatically builds V8 from source. Otherwise, you can try to download a static library from https://github.com/denoland/rusty_v8.
If that doesn't help, maybe consider opening an issue in that repository?

**Comment by rsdte** [comment]
ok, thanks for your answer.

**Comment by Bromeon** [comment]
Could you solve your issue?
